version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/acomagu/ixargs
    environment:
      - GO111MODULE: 'on'
    steps:
      - checkout
      - run:
          name: Test
          command: go test -v
